import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import localFont from "next/font/local";

const azbuki = localFont({
  src: "./fonts/Azbuki-Regular.woff2",
  preload: true,
  fallback: ["system-ui", "arial"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${azbuki.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
